# Dependencies
markdown            : kramdown
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge



# Permalinks
permalink:        pretty

# Setup
title:            Azusa's World
tagline:          'Portfolio ,experience,and skills'
description:      'News, articles and reviews'
baseurl:          https://azusa152.github.io/

author:        
  name:           'Azusa Iikubo'
  url:            https://azusa152.github.io/

paginate:         5

# Custom vars
version:          0.1.0

github_username     : azusa152
facebook_username : azusa.iikubo
linkedin__username : azusa-iikubo
gems: jekyll-paginate