# Dependencies
markdown            : kramdown
highlighter:      rouge
gems                : ["jekyll-paginate"]

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Azusa's Note
tagline:          'Portfolio ,experience,and skills'
description:      'News, articles and reviews of what i learned '
url:              https://azusa152.github.io/
baseurl:          /

author:  
  name:           'Azusa Iikubo'
  url:            https://azusa152.github.io/

paginate:         5

# Custom vars
version:          0.1.0
twitter_username    : azusa
github_username     : azusa152
facebook_username : azusa.iikubo
