# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Azusa's Resume
tagline:          'A Jekyll theme'
description:      'my resume'
url:              https://azusa152.github.io/
baseurl:          https://azusa152.github.io/

author:
  name:           'azusa'
  url:            https://azusa152.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github: 
  repo:      https://github.com/azusa152
gems: jekyll-paginate