# Dependencies
markdown            : kramdown
highlighter:      rouge
gems                : ["jekyll-paginate"]

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Azusa's Resume
tagline:          'Portfolio ,experience,and skills'
description:      'my resume'
url:              https://azusa152.github.io/
baseurl:          https://azusa152.github.io/

author:  
  name:           'Azusa Iikubo'
  url:            https://azusa152.github.io/

paginate:         5

# Custom vars
version:          0.1.0
twitter_username    : azusa
github_username     : azusa152
